Vagrant.configure("2") do |config|
   (1..3).each do |i|
   # [1].each do |i|
      
      #定义节点变量
      config.vm.define "node#{i}" do |node|
     
      # box配置
      node.vm.box = "centos7"

      # 设置虚拟机的主机名
      node.vm.hostname = "node#{i}"

      # 设置虚拟机的IP
      node.vm.network "private_network", ip: "192.168.56.#{10+i}"

      # 设置主机与虚拟机的共享目录
      # node.vm.synced_folder "/Users/meetmax", "/home/vagrant/code"
      # VirtaulBox相关配置
      node.vm.provider "virtualbox" do |v|

          # 设置虚拟机的名称
          v.name = "node#{i}"

          # 设置虚拟机的内存大小
          v.memory = 3048

          # 设置虚拟机的CPU个数
          v.cpus = 2
      end
      node.vm.provision "file", source: "../manifests/environment.sh", destination: "environment.sh"

      # 使用shell脚本进行软件安装和配置
      node.vm.provision "shell", path: "init.sh"

      end
   end
end
